development:
  adapter: postgresql 
  encoding: utf8
  database: ember_cli_admin_api_development
  pool: 5
  timeout: 5000
  host: 'localhost'

test: &test
  adapter: postgresql 
  encoding: utf8
  database: ember_cli_admin_api_test
  pool: 5
  timeout: 5000
  host: 'localhost'

production:
  adapter: postgresql 
  encoding: utf8
  database: ember_cli_admin_api
  pool: 5
  timeout: 5000
  host: 'localhost'

staging:
  adapter: postgresql 
  encoding: utf8
  database: ember_cli_admin_api_staging
  pool: 5
  timeout: 5000
  host: 'localhost'
