development:
  adapter: mysql2
  encoding: utf8
  database: ember_cli_admin_api_development
  pool: 5
  timeout: 5000
  username: root
  password:

test: &test
  adapter: mysql2
  encoding: utf8
  database: ember_cli_admin_api_test
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: ember_cli_admin_api
  pool: 5
  timeout: 5000

staging:
  adapter: mysql2
  encoding: utf8
  database: ember_cli_admin_api_staging
  pool: 5
  timeout: 5000